name: How To Science
url: http://howtoscience.net
markdown: kramdown
description: An easy-to-read student guide on how to write scientific papers and reports without the boring jargon.

# exclude during build
exclude:
  - README.md

plugins:
  - jekyll-sitemap
  - jekyll-seo-tag
  - jekyll-minifier
